insert into USER_STATE(id, SYSNAME) values (0, 'START');
insert into USER_STATE(id, SYSNAME) values (1, 'AUTHORIZATION');
insert into USER_STATE(id, SYSNAME) values (2, 'AUTHORIZED');
insert into USER_STATE(id, SYSNAME) values (3, 'FINISH');

insert into ANSWER(QUESTION_ID, RIGHT_ANSWER, TEXT) values (0, false, 'Linux');
insert into ANSWER(QUESTION_ID, RIGHT_ANSWER, TEXT) values (0, false, 'Windows');
insert into ANSWER(QUESTION_ID, RIGHT_ANSWER, TEXT) values (0, true, 'MacOS');
insert into ANSWER(QUESTION_ID, RIGHT_ANSWER, TEXT) values (1, true, 'peer2peer');
insert into ANSWER(QUESTION_ID, RIGHT_ANSWER, TEXT) values (1, false, 'school21');
insert into ANSWER(QUESTION_ID, RIGHT_ANSWER, TEXT) values (1, false, '21schoolKzn');
insert into ANSWER(QUESTION_ID, RIGHT_ANSWER, TEXT) values (1, false, 'peertopeer');
insert into ANSWER(QUESTION_ID, RIGHT_ANSWER, TEXT) values (1, false, 's21kzn');
insert into ANSWER(QUESTION_ID, RIGHT_ANSWER, TEXT) values (2, false, '2 года');
insert into ANSWER(QUESTION_ID, RIGHT_ANSWER, TEXT) values (2, false, '5 лет');
insert into ANSWER(QUESTION_ID, RIGHT_ANSWER, TEXT) values (2, true, '3 года');
insert into ANSWER(QUESTION_ID, RIGHT_ANSWER, TEXT) values (2, false, '4 года');
insert into ANSWER(QUESTION_ID, RIGHT_ANSWER, TEXT) values (3, true, 'Февраль');
insert into ANSWER(QUESTION_ID, RIGHT_ANSWER, TEXT) values (3, false, 'Март');
insert into ANSWER(QUESTION_ID, RIGHT_ANSWER, TEXT) values (3, false, 'Апрель');
insert into ANSWER(QUESTION_ID, RIGHT_ANSWER, TEXT) values (3, false, 'Август');
insert into ANSWER(QUESTION_ID, RIGHT_ANSWER, TEXT) values (3, false, 'Декабрь');
insert into ANSWER(QUESTION_ID, RIGHT_ANSWER, TEXT) values (4, false, '543');
insert into ANSWER(QUESTION_ID, RIGHT_ANSWER, TEXT) values (4, true, '557');
insert into ANSWER(QUESTION_ID, RIGHT_ANSWER, TEXT) values (4, false, '498');
insert into ANSWER(QUESTION_ID, RIGHT_ANSWER, TEXT) values (4, false, '607');
insert into ANSWER(QUESTION_ID, RIGHT_ANSWER, TEXT) values (5, false, 'edu.21.school.ru');
insert into ANSWER(QUESTION_ID, RIGHT_ANSWER, TEXT) values (5, true, 'edu.21-school.ru');
insert into ANSWER(QUESTION_ID, RIGHT_ANSWER, TEXT) values (5, false, 'edu-21.school.ru');
insert into ANSWER(QUESTION_ID, RIGHT_ANSWER, TEXT) values (5, false, 'edu-kzn.21-school.ru');
insert into ANSWER(QUESTION_ID, RIGHT_ANSWER, TEXT) values (5, false, 'edu-kazan.21-school.ru');
insert into ANSWER(QUESTION_ID, RIGHT_ANSWER, TEXT) values (6, false, 'login@student-21.school.ru');
insert into ANSWER(QUESTION_ID, RIGHT_ANSWER, TEXT) values (6, true, 'login@student.21-school.ru');
insert into ANSWER(QUESTION_ID, RIGHT_ANSWER, TEXT) values (6, false, 'login@21-school.ru');
insert into ANSWER(QUESTION_ID, RIGHT_ANSWER, TEXT) values (6, false, 'login@21.school.student.ru');